import { registerEnumType } from '@nestjs/graphql';

export enum ResponseError {
  INVALID_INPUT = 'INVALID_INPUT',

  //AUTH
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_OTP = 'INVALID_OTP',
  TWO_FACTOR_AUTHENTICATION_ENABLED = 'TWO_FACTOR_AUTHENTICATION_ENABLED',
  TWO_FACTOR_AUTHENTICATION_DISABLED = 'TWO_FACTOR_AUTHENTICATION_DISABLED',

  //ROLE
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  ROLE_DUPLICATION = 'ROLE_DUPLICATION',

  //PERMISSION
  PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND',
  PERMISSION_DUPLICATION = 'PERMISSION_DUPLICATION',

  //ADMIN
  ADMIN_NOT_FOUND = 'ADMIN_NOT_FOUND',
  ADMIN_DUPLICATION = 'ADMIN_DUPLICATION',

  //CATEGORY
  CATEGORY_DUPLICATION = 'CATEGORY_DUPLICATION',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',

  //BOOKING
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',

  //SERVICE PROVIDER
  SERVICE_PROVIDER_DUPLICATION = 'SERVICE_PROVIDER_DUPLICATION',
  SERVICE_PROVIDER_NOT_FOUND = 'SERVICE_PROVIDER_NOT_FOUND',

  //CUSTOMER
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  CUSTOMER_DUPLICATION = 'CUSTOMER_DUPLICATION',
  CUSTOMER_ALREADY_VERIFIED = 'CUSTOMER_ALREADY_VERIFIED',

  //FAVORITE SERVICE
  FAVORITE_SERVICE_NOT_FOUND = 'FAVORITE_SERVICE_NOT_FOUND',
  FAVORITE_SERVICE_DUPLICATION = 'FAVORITE_SERVICE_DUPLICATION',

  //CUSTOMER ADDRESS
  CUSTOMER_ADDRESS_NOT_FOUND = 'CUSTOMER_ADDRESS_NOT_FOUND',
}

registerEnumType(ResponseError, { name: 'ResponseError' });
